# Generated by Django 3.0.3 on 2020-05-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookBank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
        migrations.RemoveField(
            model_name='books',
            name='pdf_file',
        ),
    ]
