# Generated by Django 3.0.3 on 2020-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookBank', '0002_auto_20200518_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='books',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
 