# Generated by Django 3.0.3 on 2020-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookBank', '0003_auto_20200422_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
