# Generated by Django 3.0.3 on 2020-04-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookBank', '0005_auto_20200422_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authors',
        ),
    ]
