# Generated by Django 3.0.3 on 2020-05-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookBank', '0006_auto_20200422_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
