# Generated by Django 3.0.3 on 2020-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookBank', '0007_auto_20200506_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, default=' ', upload_to='images'),
        ),
    ]
