# Generated by Django 3.0.3 on 2020-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookBank', '0008_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf_file',
            field=models.FileField(blank=True, default=' ', upload_to='files'),
        ),
    ]
